<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Prabodh-PC" ignored="0" name="Test" tests="9" failures="1" timestamp="23 Aug 2020 12:32:04 GMT" time="148.694" errors="0">
  <testcase name="homePageNavigation" time="22.822" classname="tests.HomepageTest"/>
  <testcase name="verifyEmptyEmail" time="26.063" classname="tests.NewsletterSubsTest"/>
  <testcase name="testLogin" time="16.362" classname="tests.InvalidSignInTest"/>
  <testcase name="verifyInvalidEmail" time="25.158" classname="tests.NewsletterSubsTest"/>
  <testcase name="testLogin" time="16.105" classname="tests.InvalidSignInTest"/>
  <testcase name="verifyValidEmail" time="23.753" classname="tests.NewsletterSubsTest">
    <skipped/>
  </testcase> <!-- verifyValidEmail -->
  <testcase name="verifyValidEmail" time="23.831" classname="tests.NewsletterSubsTest">
    <skipped/>
  </testcase> <!-- verifyValidEmail -->
  <testcase name="verifyValidEmail" time="22.224" classname="tests.NewsletterSubsTest">
    <skipped/>
  </testcase> <!-- verifyValidEmail -->
  <testcase name="verifyValidEmail" time="22.322" classname="tests.NewsletterSubsTest">
    <failure type="java.lang.AssertionError" message="expected [Newsletter : You have successfully subscribed to this newsletters.] but found [Newsletter : You have successfully subscribed to this newsletter.]">
      <![CDATA[java.lang.AssertionError: expected [Newsletter : You have successfully subscribed to this newsletters.] but found [Newsletter : You have successfully subscribed to this newsletter.]
at tests.NewsletterSubsTest.verifyValidEmail(NewsletterSubsTest.java:59)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyValidEmail -->
</testsuite> <!-- Test -->
