<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="Prabodh-PC" name="tests.NewsletterSubsTest" tests="6" failures="1" timestamp="23 Aug 2020 12:32:05 GMT" time="147.554" errors="0">
  <testcase name="verifyValidEmail" time="24.389" classname="tests.NewsletterSubsTest">
    <skipped/>
  </testcase> <!-- verifyValidEmail -->
  <testcase name="verifyInvalidEmail" time="25.802" classname="tests.NewsletterSubsTest"/>
  <testcase name="verifyValidEmail" time="23.045" classname="tests.NewsletterSubsTest">
    <failure type="java.lang.AssertionError" message="expected [Newsletter : You have successfully subscribed to this newsletters.] but found [Newsletter : You have successfully subscribed to this newsletter.]">
      <![CDATA[java.lang.AssertionError: expected [Newsletter : You have successfully subscribed to this newsletters.] but found [Newsletter : You have successfully subscribed to this newsletter.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at tests.NewsletterSubsTest.verifyValidEmail(NewsletterSubsTest.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyValidEmail -->
  <testcase name="verifyValidEmail" time="22.846" classname="tests.NewsletterSubsTest">
    <skipped/>
  </testcase> <!-- verifyValidEmail -->
  <testcase name="verifyValidEmail" time="24.490" classname="tests.NewsletterSubsTest">
    <skipped/>
  </testcase> <!-- verifyValidEmail -->
  <testcase name="verifyEmptyEmail" time="26.982" classname="tests.NewsletterSubsTest"/>
</testsuite> <!-- tests.NewsletterSubsTest -->
